Repository 9776mk/final_pjt, pull requests merged in 2022-12, with the labels that each got.

#67 feat(articles): 좋아요 비동기
  accounts/migrations/0002_auto_20221201_0923.py
  articles/migrations/0002_auto_20221201_1102.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/urls.py
  articles/views.py
Labels: feat

#70 test: 카테고리 진행중
  crawling/crawling.py
  requirements.txt
Labels: test

#73 솔브드 크롤링
  crawling/crawling.py
Labels: etc

#75 저장을 안하고 푸쉬했네여
  crawling/crawling.py
Labels: etc

#84 Stack multi
  accounts/forms.py
  accounts/migrations/0005_profile_stack.py
  accounts/models.py
  algorithm/settings.py
  templates/base.html
Labels: fix, refactor

#85 style: 게시판 detail - 좋아요 댓글은 아직 안함
  articles/templates/articles/detail.html
  scss/board_detail.scss
  static/css/board_detail.css
  static/css/board_detail.css.map
Labels: style

#86 etc: 게시판 create 이미지폼 수정
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  scss/board_detail.scss
  static/css/board_detail.css
Labels: style, etc

#89 feat: 쪽지 기능
  articles/views.py
  notes/templates/notes/detail.html
  notes/templates/notes/index.html
  notes/templates/notes/send.html
  notes/urls.py
  notes/views.py
  requirements.txt
  static/css/base.css
Labels: feat

#90 모델추가 및 통계수정
  accounts/migrations/0006_alter_profile_language.py
  accounts/models.py
  articles/templates/articles/home.html
  articles/views.py
  crawling.py
  crawling/problems.json
Labels: feat, fix, refactor, etc

#91 etc: 게시판 detail 자잘한 수정, 버튼 수정 등
  articles/templates/articles/detail.html
  scss/board_detail.scss
  static/css/base.css
  static/css/board.css
  static/css/board_detail.css
  static/css/board_detail.css.map
Labels: etc

#101 feat(articles): 게시판 작성 에디터 추가
  articles/migrations/0005_alter_article_content.py
  articles/models.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/views.py
  final_pjt/settings.py
  requirements.txt
Labels: feat

#102 style: 게시판 전반 디자인 수정 - 임시로 해둔것!
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  scss/board_create.scss
  scss/board_detail.scss
  static/css/base.css
  static/css/board.css
  static/css/board_create.css
  static/css/board_create.css.map
  static/css/board_detail.css
  static/css/board_detail.css.map
  static/images/likes.png
Labels: style, etc

#103 test: 저장 완료
  algorithm/migrations/0001_initial.py
  algorithm/migrations/0002_rename_bjdata_bjdata_1.py
  algorithm/migrations/__init__.py
  algorithm/models.py
  crawling.py
  crawling/crawling2.py
  db_save.py
  problems.json
Labels: test

#104 style: 게시판 테두리, 카테고리 색 입히기, tab 연결 아직 안함
  articles/migrations/0006_merge_20221204_2302.py
  articles/templates/articles/create.html
  articles/templates/articles/index.html
  scss/board_create.scss
  static/css/base.css
  static/css/board.css
  static/css/board_create.css
  static/css/board_create.css.map
Labels: style, etc

#105 feat(algorithm): 크롤링 기능 추가
  algorithm/migrations/0003_auto_20221205_0002.py
  algorithm/models.py
  articles/migrations/0006_merge_20221205_0001.py
  boj.py
  crawling.py
  problems.json
Labels: feat

#106 feat(accounts): 프로필 백준 티어 추가
  accounts/templates/accounts/profile.html
  accounts/views.py
  boj.py
Labels: feat

#108 fix: accounts 백준 아이디 없는 경우 에러 수정
  accounts/views.py
Labels: fix

#111 fix: crawling 태그 없을 때 발생하는 오류
  algorithm/templates/algorithm/index.html
  algorithm/views.py
  crawling.py
  problems.json
Labels: fix

#112 설문 조사 페이지fe
  articles/migrations/0008_merge_20221205_1402.py
  articles/templates/articles/home.html
  static/css/servey.css
  static/js/servey.js
  surveys/migrations/0003_auto_20221205_1412.py
  surveys/models.py
  surveys/templates/surveys/create.html
  surveys/views.py
Labels: style, etc

#115 style: 방명록 말풍선 수정
  accounts/templates/accounts/guestbook.html
  accounts/templates/accounts/profile.html
  articles/migrations/0001_initial.py
  articles/migrations/0007_merge_20221205_0913.py
  articles/migrations/0007_merge_20221205_0924.py
  articles/migrations/0008_merge_20221205_1402.py
  static/css/guestbook.css
Labels: style, etc

#119 style: 게시판 자잘한 수정, detail 댓글
  articles/migrations/0007_merge_20221205_1107.py
  articles/templates/articles/detail.html
  articles/views.py
  scss/board_detail.scss
  static/css/base.css
  static/css/board.css
  static/css/board_detail.css
  static/css/board_detail.css.map
  static/images/likes.png
  templates/base.html
Labels: style, etc

#120 etc: views.py 복구
  articles/migrations/0007_merge_20221205_1107.py
  articles/views.py
Labels: etc

#121 설문조사 오류/리다이렉트
  static/css/servey.css
  static/css/surveyIndex.css
  surveys/templates/surveys/create.html
  surveys/templates/surveys/index.html
  surveys/views.py
Labels: fix, style

#123 style: navbar에 알림창 modal 붙임
  templates/base.html
Labels: style

#124 fix: 쪽지 비동기 수정
  notes/templates/notes/trash.html
  notes/views.py
  templates/base.html
Labels: fix

#125 긴화면에 Top버튼 적용
  articles/templates/articles/home.html
  scss/mainpage.scss
  scss/surveyIndex.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/css/surveyIndex.css
  static/css/surveyIndex.css.map
  static/js/mainpage.js
  static/js/surveyIndex.js
  surveys/templates/surveys/index.html
Labels: feat, style

#126 fix: 쪽지 휴지통에 다른사람이 삭제한 쪽지가 들어가는 오류
  articles/migrations/0001_initial.py
  notes/templates/notes/detail.html
  notes/templates/notes/important.html
  notes/templates/notes/index.html
  notes/templates/notes/trash.html
  notes/views.py
  static/css/notes.css
Labels: fix

#128 버튼스타일
  scss/mainpage.scss
  scss/surveyIndex.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/css/servey.css
  static/css/surveyIndex.css
  static/css/surveyIndex.css.map
Labels: style

#129 style: 게시판 pagination
  articles/templates/articles/index.html
  articles/views.py
  static/css/board.css
Labels: style

#132 style: 쪽지함
  notes/templates/notes/detail.html
  notes/templates/notes/important.html
  notes/templates/notes/index.html
  notes/templates/notes/send.html
  notes/templates/notes/trash.html
  notes/views.py
  static/css/notes.css
Labels: style

#137 style: notes detail
  notes/templates/notes/detail.html
  notes/templates/notes/important.html
  notes/templates/notes/index.html
  notes/templates/notes/trash.html
  notes/views.py
  static/css/notes.css
Labels: style, etc

#138 test: 카테고리 생성 중
  algorithm/forms.py
  algorithm/migrations/0004_tag.py
  algorithm/models.py
  algorithm/templates/algorithm/index.html
  algorithm/templates/algorithm/search.html
  algorithm/urls.py
  algorithm/views.py
  algorithm/widgets.py
Labels: test

#146 fix: login시 쪽지 알림 오류
  accounts/views.py
  notes/views.py
  templates/base.html
Labels: fix

#147 test: level별 db 검색 기능 구현
  algorithm/migrations/0005_bjdata_total.py
  algorithm/models.py
  algorithm/templates/algorithm/index.html
  algorithm/templates/algorithm/search.html
  algorithm/templates/algorithm/widgets/custom_checkbox.html
  algorithm/templates/algorithm/widgets/custom_checkbox_option.html
  algorithm/views.py
  static/js/problem_category.js
Labels: test

#148 style: 게시판 카테고리 탭
  articles/templates/articles/index.html
  articles/urls.py
  articles/views.py
  static/css/board.css
Labels: style

#151 style: 벗삼기/찾기 fe + 반응형
  friends/templates/friends/index.html
  scss/friends_index.scss
  static/css/friends_index.css
  static/css/friends_index.css.map
Labels: style

#152 Sb 27
  accounts/templates/accounts/password.html
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_update.html
  accounts/urls.py
  accounts/views.py
  articles/views.py
  static/css/base.css
Labels: feat

#153 메인알고리즘
  articles/templates/articles/home.html
  articles/views.py
  scss/mainpage.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/js/mainpage.js
Labels: feat, style

#156 회원가입/메인 수정
  accounts/templates/accounts/signup.html
  articles/templates/articles/friend.html
  articles/templates/articles/home.html
  scss/mainpage.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/css/signup.css
Labels: fix, style

#157 fix(articles): 게시판 텍스트에디터에서 마크다운으로 변경
  accounts/views.py
  articles/migrations/0001_initial.py
  articles/models.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/templatetags/filter.py
  articles/views.py
  final_pjt/settings.py
  requirements.txt
Labels: fix

#158 style: 벗, 추천결과 fe, 기본버튼 디자인 변경 등
  friends/templates/friends/index.html
  friends/templates/friends/recommend.html
  scss/board_create.scss
  scss/friends_index.scss
  static/css/base.css
  static/css/board_create.css
  static/css/friends_index.css
  static/css/friends_index.css.map
Labels: style

#159 feat: 쪽지 답장보내기
  notes/forms.py
  notes/templates/notes/detail.html
  notes/templates/notes/index.html
  notes/templates/notes/reply.html
  notes/templates/notes/send.html
  notes/urls.py
  notes/views.py
  static/css/base.css
Labels: feat

#160 rank구현
  .gitignore
  articles/templates/articles/home.html
  articles/views.py
  scss/mainpage.scss
  static/css/login.css
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/images/crown.png
Labels: feat, fix, style

#162 style: 게시판, navbar 반응형, 자잘한 수정
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  friends/templates/friends/recommend.html
  scss/board_detail.scss
  scss/friends_index.scss
  static/css/board.css
  static/css/board_detail.css
  static/css/board_detail.css.map
  static/css/friends_index.css
  static/css/friends_index.css.map
  templates/base.html
Labels: style

#163 설문조사/메인 수정
  articles/templates/articles/home.html
  articles/views.py
  scss/mainpage.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/js/servey.js
  surveys/templates/surveys/create.html
  templates/base.html
Labels: fix, style

#165 test: 알고리즘 검색 진행중
  algorithm/views.py
  crawling.py
  problems.json
Labels: test

#168 style: 게시판 반응형 완료
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  scss/board_create.scss
  scss/board_detail.scss
  static/css/board_create.css
  static/css/board_create.css.map
  static/css/board_detail.css
  static/css/board_detail.css.map
Labels: style

#169 etc: 게시판 댓글 작성 폼 반응형 추가
  articles/templates/articles/detail.html
  scss/board_detail.scss
  static/css/board_detail.css
  static/css/board_detail.css.map
Labels: etc

#171 etc: navbar 스터디 추가
  templates/base.html
Labels: etc

#172 style: 스터디 index, detail 버튼 등 수정
  scss/board_detail.scss
  scss/studies.scss
  static/css/board_detail.css
  static/css/board_detail.css.map
  static/css/studies.css
  studies/templates/studies/detail.html
  studies/templates/studies/index.html
Labels: style

#173 수정
  accounts/models.py
  friends/views.py
Labels: etc

#174 surveys/index수정
  scss/surveyIndex.scss
  static/css/surveyIndex.css
  static/css/surveyIndex.css.map
  surveys/templates/surveys/create.html
  surveys/templates/surveys/index.html
Labels: fix

#175 메인top버튼 수정
  scss/mainpage.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
Labels: fix

#177 style: footer 반응형
  static/css/base.css
  templates/base.html
Labels: style

#182 test: 검색 기능 추가중
  algorithm/templates/algorithm/index.html
  algorithm/templates/algorithm/search.html
  algorithm/views.py
  crawling.py
  problems.json
Labels: test

#183 feat(algorithm): 검색 기능 추가
  algorithm/views.py
Labels: feat

#189 글작성fe/main fe
  articles/forms.py
  articles/templates/articles/detail.html
  articles/templates/articles/home.html
  scss/mainpage.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/images/devel.png
Labels: fix, style

#190 feat(signup): 백준 아이디 확인 추가
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  algorithm/templates/algorithm/index.html
  db_union.py
  static/js/signup.js
Labels: feat

#191 개발마당 글 작성 textarea스타일
  articles/forms.py
Labels: style

#192 feat(accounts): git 아이디 확인 추가
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  static/js/signup.js
Labels: feat

#193 Sb 33
  accounts/migrations/0005_remove_user_message_number.py
  accounts/models.py
  accounts/views.py
  notes/templates/notes/detail.html
  notes/templates/notes/important.html
  notes/templates/notes/index.html
  notes/templates/notes/reply.html
  notes/templates/notes/send.html
  notes/templates/notes/send_to.html
  notes/templates/notes/trash.html
  notes/views.py
  static/css/notes.css
  templates/base.html
Labels: fix, style

#199 Th34
  accounts/templates/accounts/signup.html
  algorithm/templates/algorithm/index.html
  articles/templates/articles/home.html
  scss/mainpage.scss
  static/css/algo_index.css
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/css/signup.css
  static/images/find.png
Labels: style

#203 스터디 반응형/메인 반응/ 알고리즘 버튼수정
  friends/templates/friends/index.html
  scss/mainpage.scss
  static/css/algo_index.css
  static/css/mainpage.css
  static/css/mainpage.css.map
  studies/templates/studies/index.html
Labels: style

#205 etc: navbar 이름 수정, 벗삼기 반응형 수정 등
  articles/templates/articles/detail.html
  scss/board_create.scss
  scss/board_detail.scss
  scss/friends_index.scss
  scss/studies.scss
  static/css/board_create.css
  static/css/board_create.css.map
  static/css/board_detail.css
  static/css/board_detail.css.map
  static/css/friends_index.css
  static/css/friends_index.css.map
  static/css/studies.css
  studies/templates/studies/create.html
  studies/templates/studies/detail.html
  templates/base.html
Labels: etc

#206 fix(studies): 스터디 수정 시 제목, 연락처 제대로 못 받아오는 오류 수정
  studies/templates/studies/create.html
  studies/templates/studies/update.html
Labels: fix

#208 알고리즘 검색 테이블
  algorithm/templates/algorithm/search.html
  algorithm/views.py
  static/css/search.css
Labels: style

#212 Sb 35
  accounts/migrations/0006_alter_profile_intro.py
  accounts/models.py
  accounts/templates/accounts/guestbook.html
  accounts/templates/accounts/profile.html
  accounts/views.py
  articles/urls.py
  articles/views.py
  notes/views.py
  static/css/guestbook.css
  static/css/profile.css
  static/js/accounts_gb_article_async.js
Labels: style, etc

#217 style: 댓글 마크다운 형식으로 변경
  articles/forms.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  scss/board_detail.scss
  static/css/board_detail.css
  static/css/board_detail.css.map
  studies/templates/studies/create.html
Labels: style, etc

#219 개발마당버튼/벗찾기 사용자fe ing..
  accounts/templates/accounts/profile_update.html
  algorithm/templates/algorithm/index.html
  articles/templates/articles/index.html
  friends/templates/friends/index.html
  static/css/board.css
Labels: style

#221 벗 사용자 목록 fe
  friends/templates/friends/index.html
Labels: style

#222 개발마당 검색
  articles/templates/articles/index.html
  static/css/board.css
Labels: style

#223 알고리즘 버튼 스타일
  scss/mainpage.scss
  static/css/algo_index.css
  static/css/mainpage.css
  static/css/mainpage.css.map
Labels: style

#224 Sb 36
  accounts/templates/accounts/profile.html
  notes/forms.py
  notes/migrations/0002_notes_to_id.py
  notes/models.py
  notes/templates/notes/important.html
  notes/templates/notes/index.html
  notes/templates/notes/send.html
  notes/templates/notes/trash.html
  notes/views.py
  static/css/base.css
  static/images/note.png
  templates/base.html
Labels: fix, style, etc

#226 style: 스터디 detail fe, 반응형
  articles/forms.py
  scss/studies.scss
  static/css/studies.css
  studies/templates/studies/detail.html
Labels: style

#227 회원가입/로그인 배경
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  static/css/login.css
  static/css/signup.css
Labels: style

#229 style
  accounts/templates/accounts/profile.html
  articles/templates/articles/index.html
  friends/templates/friends/index.html
  friends/templates/friends/recommend.html
Labels: style

#233 style: articles search fe, 스터디 detail 버튼 수정
  articles/templates/articles/index.html
  articles/templates/articles/search.html
  articles/urls.py
  articles/views.py
  scss/studies.scss
  static/css/studies.css
  studies/templates/studies/detail.html
Labels: style

#236 Sb 37
  accounts/templates/accounts/guestbook.html
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/views.py
  notes/templates/notes/detail.html
  notes/templates/notes/index.html
  notes/views.py
  static/css/guestbook.css
  static/css/surveyIndex.css
  static/js/accounts_gb_article_async.js
  surveys/templates/surveys/create.html
  surveys/templates/surveys/index.html
  templates/base.html
Labels: feat, style

#237 test(studies): 스터디 게시판 만드는 중
  studies/forms.py
  studies/migrations/0012_article_articlecomment.py
  studies/migrations/0013_article_article.py
  studies/migrations/0014_rename_article_article_study.py
  studies/migrations/0015_auto_20221213_0231.py
  studies/migrations/0016_board_category.py
  studies/models.py
  studies/templates/studies/board.html
  studies/templates/studies/board_create.html
  studies/templates/studies/board_detail.html
  studies/templates/studies/create.html
  studies/urls.py
  studies/views.py
Labels: test

#243 fix: 공부방 빈 이미지 문제 해결
  articles/templates/articles/home.html
  studies/templates/studies/index.html
Labels: etc

#244 fix: 회원탈퇴 수정/자잘한 수정
  accounts/templates/accounts/profile_update.html
  accounts/urls.py
  accounts/views.py
  notes/urls.py
  notes/views.py
Labels: fix

#245 이미지 팝업확대
  articles/templates/articles/detail.html
  articles/templates/articles/home.html
  scss/board_detail.scss
  scss/mainpage.scss
  static/css/board_detail.css
  static/css/board_detail.css.map
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/js/board_detail.js
Labels: feat, style

#251 main Style
  scss/mainpage.scss
  static/css/login.css
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/css/signup.css
Labels: fix, style

#252 etc: articles search 말줄임표, 조회수 추가
  articles/templates/articles/index.html
  articles/templates/articles/search.html
Labels: etc

#254 articles/img
  articles/templates/articles/detail.html
  scss/board_detail.scss
  static/css/board_detail.css
  static/css/board_detail.css.map
Labels: fix

#255 벗.호버
  static/css/board.css
  studies/templates/studies/index.html
Labels: style

#258 Sb 40
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  notes/templates/notes/detail.html
  notes/templates/notes/index.html
  notes/templates/notes/trash.html
  static/css/notes.css
  static/css/surveyIndex.css
  templates/base.html
  templates/base_dark.html
Labels: style, etc

#259 etc: 문제 풀었는지 확인/ 게시판 index, detail 진행 중
  boj_check.py
  studies/models.py
  studies/templates/studies/board_detail.html
  studies/templates/studies/board_index.html
  studies/templates/studies/detail.html
  studies/urls.py
  studies/views.py
Labels: etc

#260 etc: board scss 파일 추가, 문제집 가로줄 추가 등
  algorithm/templates/algorithm/index.html
  scss/board.scss
  static/css/board.css
  static/css/board_detail.css.map
Labels: etc

#261 etc: scss 파일 호버 부분 빠진거 채움
  scss/board.scss
Labels: etc

#263 test(studies): 디테일에서 유저 문제 확인
  studies/templates/studies/board_detail.html
  studies/views.py
Labels: test

#266 fix: detail 페이지에서 프로필 이미지, 스터디 게시판 이미지 설정 충돌
  articles/templates/articles/detail.html
  scss/board.scss
  scss/board_detail.scss
  scss/studies.scss
  static/css/board.css
  static/css/board_detail.css
  static/css/board_detail.css.map
  static/css/studies.css
Labels: fix

#270 feat(studies): 사용자 문제 풀이 확인
  studies/templates/studies/board_detail.html
  studies/views.py
Labels: feat

#274 스터디 게시판 디테일
  scss/study_detail.scss
  static/css/study_detail.css
  studies/templates/studies/board_detail.html
  studies/views.py
Labels: style

#275 feat: 스터디 검색 기능 추가
  scss/board.scss
  static/css/board.css
  studies/templates/studies/index.html
  studies/templates/studies/search.html
  studies/urls.py
  studies/views.py
Labels: feat

#276 feat(accounts): signup때 아이디가 유효하지 않으면 초기화
  static/js/signup.js
Labels: feat

#277 주석을 안풀었네
  studies/views.py
Labels: fix

#278 fix 스터디 게시판/조회수 수정
  articles/urls.py
  notes/views.py
  studies/views.py
Labels: fix

#280 스터디 디테일 문제일경우..
  studies/templates/studies/board_index.html
  studies/views.py
Labels: fix

#281 chore: notes
  notes/templates/notes/index.html
Labels: etc

#282 test(studies): 게시글 수정/삭제
  studies/templates/studies/board_detail.html
  studies/urls.py
  studies/views.py
Labels: feat, test

#285 test(studies): 게시글 수정/삭제
  studies/templates/studies/board_detail.html
  studies/views.py
Labels: test

#286 chore: password 변경 페이지
  accounts/templates/accounts/password.html
Labels: etc

#298 style: 공부방 게시판 index 수정
  scss/board.scss
  static/css/board.css
  studies/templates/studies/board_index.html
  studies/views.py
Labels: style

#300 파비콘
  static/images/favi.png
  templates/base.html
  templates/base_dark.html
Labels: style
