Repository 9776mk/final_pjt, pull requests merged in 2022-11, with the labels that each got.

#7 feat(articles): 게시글 사진 작성 (수정X)
  articles/forms.py
  articles/migrations/0002_auto_20221127_1841.py
  articles/models.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/views.py
  final_pjt/settings.py
  requirements.txt
Labels: enhancement, help wanted

#8 feat: navbar 생성
  articles/templates/articles/home.html
  articles/views.py
  final_pjt/urls.py
  templates/base.html
Labels: feat

#11 static경로설정
  accounts/templates/accounts/signup.html
  final_pjt/settings.py
  static/css/base.css
  static/css/signup.css
  templates/base.html
Labels: etc

#15 style: navbar 수정
  templates/base.html
Labels: style

#16 style: profile 수정
  accounts/templates/accounts/profile.html
Labels: style

#18 etc: navbar url 연결
  articles/templates/articles/index.html
  templates/base.html
Labels: etc

#19 style: profile 수정
  accounts/templates/accounts/profile.html
Labels: style

#20 etc: navbar 수정
  static/css/base.css
  templates/base.html
Labels: etc

#24 fix
  accounts/templates/accounts/signup.html
  static/css/signup.css
Labels: fix

#27 style: 게시판, navbar 수정
  articles/templates/articles/index.html
  static/css/base.css
  templates/base.html
Labels: style

#29 nav 조금 게시판 조금 수정
  articles/templates/articles/index.html
  static/css/base.css
  templates/base.html
Labels: etc

#35 로그인 분기처리
  accounts/templates/accounts/login.html
  accounts/views.py
Labels: feat

#36 회원가입 소개문구 변경
  accounts/templates/accounts/signup.html
  static/css/signup.css
Labels: etc

#38 etc: navbar user image 오류 수정
  templates/base.html
Labels: etc

#40 fix: css 괄호 수정
  static/css/base.css
Labels: fix

#42 feat: git 연동 로그인
  accounts/exception.py
  accounts/forms.py
  accounts/migrations/0006_auto_20221127_2333.py
  accounts/migrations/0007_alter_user_email.py
  accounts/migrations/0008_auto_20221128_1719.py
  accounts/migrations/0009_auto_20221129_1123.py
  accounts/models.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  requirements.txt
  templates/base.html
Labels: feat

#48 etc: navbar 수정 - 메뉴랑 사용자
  templates/base.html
Labels: etc

#50 feat(articles): 댓글 비동기 생성수정/ 삭제(비동기)추가
  accounts/migrations/0011_merge_20221129_1638.py
  accounts/migrations/0012_auto_20221129_1640.py
  accounts/migrations/0013_merge_20221130_1124.py
  accounts/urls.py
  articles/migrations/0002_auto_20221130_1132.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/views.py
Labels: feat, fix

#51 fix(accounts): 깃허브 연동 시 자동으로 회원가입 및 로그인
  accounts/migrations/0013_merge_0012_auto_20221129_1553_0012_auto_20221129_1613.py
  accounts/templates/accounts/profile.html
  accounts/views.py
  static/js/accounts_follow_async.js
  templates/base.html
Labels: fix, etc

#55 main fe
  articles/templates/articles/home.html
  scss/mainpage.scss
  scss/test.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
Labels: style

#57 통계 그래프 적용
  articles/templates/articles/home.html
  scss/mainpage.scss
  static/css/mainpage.css
  static/css/mainpage.css.map
  static/js/mainpage.js
Labels: feat, style, etc

#58 graph
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_auto_20221130_1504.py
  accounts/migrations/0013_merge_0012_auto_20221129_1553_0012_auto_20221129_1613.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_auto_20221130_1132.py
  articles/templates/articles/home.html
  articles/views.py
Labels: feat, style, etc

#59 fix: home - 계산식 ZeroDivisionError fix
  articles/views.py
Labels: fix

#63 test: 번호, 제목 완료
  crawling/crawling.py
Labels: test
